# Generated by Django 2.2.13 on 2020-10-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcatagorymodel',
            name='id',
        ),
        migrations.AddField(
            model_name='subcatagorymodel',
            name='subid',
            field=models.AutoField(default=False, primary_key=True, serialize=False),
        ),
    ]
