# Generated by Django 2.2.13 on 2020-10-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20201010_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllDeatilsModel',
            fields=[
                ('aidno', models.AutoField(primary_key=True, serialize=False)),
                ('catagory', models.CharField(max_length=30)),
                ('subcatagory', models.CharField(max_length=40)),
                ('types', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='catagorymodel',
            name='catid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subcatagorymodel',
            name='subid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
